"""add tags and updated_at to handbooks table

Revision ID: 8171b6ddeeb3
Revises: 8bd73e65e8b8
Create Date: 2025-07-05 21:15:44.786440

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '8171b6ddeeb3'
down_revision = '8bd73e65e8b8'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handbooks', schema=None) as batch_op:
        batch_op.add_column(sa.Column('tags', sa.String(length=255), nullable=True))

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('handbooks', schema=None) as batch_op:
        batch_op.drop_column('tags')

    # ### end Alembic commands ###
